% =============================================================================
% Project      : UART Transmitter Verification
% File         : uart_analysis.m
% Author       : Yashika Paharia
% Description  : MATLAB script that does two things:
%                  1. Generates test vectors written to sim/test_vectors.txt
%                     (used as reference — the SV testbench has its own tests)
%                  2. Plots an annotated UART waveform so you can visually
%                     verify the bit ordering and timing look correct
%
% Background:
%   UART 8N1 frame: [IDLE | START bit (0) | D0 D1 D2 D3 D4 D5 D6 D7 | STOP (1) | IDLE]
%   Bits are sent LSB first. Each bit lasts 1/baud_rate seconds.
% =============================================================================

clc; clear; close all;

fprintf('==============================================\n');
fprintf('  UART TX - MATLAB Verification Helper\n');
fprintf('  Author: Yashika Paharia\n');
fprintf('==============================================\n\n');

%% -----------------------------------------------------------
%  Part 1: Write out the bytes we plan to test
%  (These match the directed tests in the SV testbench)
%% -----------------------------------------------------------
fprintf('[1/2] Writing test vector reference file...\n');

if ~exist('sim', 'dir'), mkdir('sim'); end

% Each row: {hex value, short label}
test_cases = {
    0x41, 'ASCII_A';
    0x42, 'ASCII_B';
    0x43, 'ASCII_C';
    0x00, 'All_zeros';
    0xFF, 'All_ones';
    0xAA, 'Alternating_10';
    0x55, 'Alternating_01';
};

fid = fopen('sim/test_vectors.txt', 'w');
fprintf(fid, '%% UART TX test vectors - generated by uart_analysis.m\n');
fprintf(fid, '%% Format: hex_value  label\n');
for i = 1:size(test_cases, 1)
    fprintf(fid, '%02x  %s\n', test_cases{i,1}, test_cases{i,2});
end
fclose(fid);

fprintf('   Wrote %d entries to sim/test_vectors.txt\n\n', size(test_cases,1));

%% -----------------------------------------------------------
%  Part 2: Model and plot the UART waveform for one example byte
%
%  Plotting the expected waveform before simulation is useful:
%  it lets you visually check the bit order and timing, then
%  compare against the actual VCD waveform from GTKWave.
%% -----------------------------------------------------------
fprintf('[2/2] Generating annotated UART waveform plot...\n');

baud_rate    = 115200;          % bits per second
clk_freq     = 25e6;            % 25 MHz system clock
clks_per_bit = round(clk_freq / baud_rate);  % = 217 cycles
bit_period   = 1 / baud_rate;   % seconds per bit

example_byte = 0x4A;            % 'J' - just a nice example to plot
fprintf('   Plotting UART frame for byte 0x%02X ("%s")\n', example_byte, char(example_byte));

% Build the frame: idle -> start -> 8 data bits (LSB first) -> stop -> idle
data_bits  = bitand(bitshift(example_byte, -(0:7)), 1);   % extract bits 0-7
uart_frame = [1, 0, data_bits, 1, 1];                      % idle-start-data-stop-idle

% Oversample each bit so stairs() draws clean edges
oversample = 10;
t_wave = [];
s_wave = [];
for k = 1:length(uart_frame)
    t_wave = [t_wave, linspace((k-1)*bit_period, k*bit_period, oversample)];
    s_wave = [s_wave, repmat(uart_frame(k), 1, oversample)];
end
t_us = t_wave * 1e6;  % convert to microseconds for the x-axis

% --- Build the figure ---
fig = figure('Position', [100 100 950 380], 'Color', 'white');

stairs(t_us, s_wave, 'b-', 'LineWidth', 2.2);
hold on;

% Shade each bit region with a background color and label
region_labels = ['IDLE', 'STR ', compose("D%d", 0:7), 'STP ', 'IDLE'];
bg_colors = {
    [0.88 0.88 0.88], ...   % idle
    [1.00 0.78 0.78], ...   % start bit (red-ish)
    [0.80 0.95 0.80], [0.80 0.95 0.80], [0.80 0.95 0.80], [0.80 0.95 0.80], ...  % data bits
    [0.80 0.95 0.80], [0.80 0.95 0.80], [0.80 0.95 0.80], [0.80 0.95 0.80], ...
    [1.00 0.90 0.70], ...   % stop bit (yellow-ish)
    [0.88 0.88 0.88]        % idle
};

for k = 1:length(uart_frame)
    x0 = (k-1) * bit_period * 1e6;
    x1 =  k    * bit_period * 1e6;
    patch([x0 x1 x1 x0], [-0.12 -0.12 1.12 1.12], ...
          bg_colors{k}, 'EdgeColor', 'none', 'FaceAlpha', 0.45);
    % Region label below the axis
    text(x0 + (x1-x0)/2, -0.25, region_labels{k}, ...
         'HorizontalAlignment', 'center', 'FontSize', 8.5, 'FontWeight', 'bold');
    % Bit value inside the waveform
    text(x0 + (x1-x0)/2, 0.55, num2str(uart_frame(k)), ...
         'HorizontalAlignment', 'center', 'FontSize', 10, 'Color', [0.1 0.1 0.6], ...
         'FontWeight', 'bold');
end

ylim([-0.40 1.30]);
xlim([0, length(uart_frame) * bit_period * 1e6]);
xlabel('Time (\mus)', 'FontSize', 11);
ylabel('TX Line', 'FontSize', 11);
yticks([0 1]); yticklabels({'0 (Low)', '1 (High)'});
title(sprintf('UART TX Waveform: 0x%02X (''%s'')  |  115200 baud  |  LSB first', ...
    example_byte, char(example_byte)), 'FontSize', 12, 'FontWeight', 'bold');
grid on; box on;

% Print baud rate timing info as a text annotation
timing_note = sprintf('Bit period = %.1f \\mus  |  CLKS\\_PER\\_BIT = %d  |  Clock = 25 MHz', ...
    bit_period*1e6, clks_per_bit);
text(0.5, 1.22, timing_note, 'Units', 'data', ...
     'HorizontalAlignment', 'left', 'FontSize', 9, 'Color', [0.35 0.35 0.35]);

saveas(fig, 'sim/uart_waveform.png');
fprintf('   Saved plot to sim/uart_waveform.png\n\n');

fprintf('==============================================\n');
fprintf('  Done. Next step: run the simulation.\n');
fprintf('    bash sim/run_sim.sh iverilog\n');
fprintf('==============================================\n');
